### ISSUE TITLE
As a user, I want to have a nice UI showing orders and customers

### ISSUE THREAD

**Issue by punnyhuimin** [AY2122S2-CS2103-F09-4/tp#115]
... so that I can easily see them

**Comment by darshan152** [comment]
This was deprioritized right? Shall we close/ remove the issue from 1.3?

**Comment by punnyhuimin** [comment]
> This was deprioritized right? Shall we close/ remove the issue from 1.3?

I kept it to make the UI changes and tag it to this issue. Let me move it to v1.3b.
