### ISSUE TITLE
[PE-D] Delivery Date feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-4/tp#191]
Delivery Date can be set to before current date and time via edito command.

![image.png](https://raw.githubusercontent.com/lzf834/ped/main/files/fa97c86e-bbe6-4f47-8cd3-eb6383c72254.png)

Command used:
edito c/01-01-2022 10:30

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lzf834/ped#4

**Comment by Geralddtan** [comment]
This seems to be an expected feature as we want to allow flexibility by accepting dates in the past for record keeping purposes. This has been written into the UserGuide.
