### ISSUE TITLE
[PE-D] Adding a new person disallowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-4/tp#198]
![Screenshot 2022-04-01 at 2.43.08 PM.png](https://raw.githubusercontent.com/gigituang/ped/main/files/86a7e6ee-b5dd-4cd5-a5cd-e7bc954bd636.png)

Adding a new person weird090II that does not exist in the list, but there was an error message showing it already exist.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: gigituang/ped#2

**Comment by Geralddtan** [comment]
To update UG on unique person condition

**Comment by punnyhuimin** [comment]
> To update UG on unique person condition

Specifically to mention that the phone number and name needs to be unique.
