### ISSUE TITLE
[PE-D] Validation improvement for date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F09-4/tp#200]
![6.PNG](https://raw.githubusercontent.com/aaron-ljx/ped/main/files/5942c149-407a-4295-b2fc-da3e55a980dd.PNG)

Perhaps would be nice to set a minimum bound for the year so that it wouldn't be possible to enter a ridiculous looking year.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: aaron-ljx/ped#4

**Comment by Geralddtan** [comment]
We allow dates in the past for increased flexibility for the user (even if its far before). Thus, we will not be implementing this issue and will be closing it.
