### ISSUE TITLE
[PE-D] Unable to see both customer and order list at the same time

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-4/tp#212]
Because of this, I have to keep typing listp and listo back and forth to check between customers which have orders and customers which don't have orders. As a user, I find it extremely annoying. Maybe it would be great to differentiate between customers that have or don't have orders with a simple tag.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: aaron-ljx/ped#5

**Comment by darshan152** [comment]
Adding a second panel will be a violation of the feature freeze, thus we will not be adding it in
