### ISSUE TITLE
[PE-D] Unnecessary tags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F09-4/tp#214]
![Capture.PNG](https://raw.githubusercontent.com/aaron-ljx/ped/main/files/9c43c41c-2dbc-4e6c-b7fb-693c133d2d4d.PNG)

Not sure what the tags are there for. Does the bakers need to know that the customers are their friends or neighbors? 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: aaron-ljx/ped#6

**Comment by punnyhuimin** [comment]
Might be a Windows issue. Working fine on Mac.
