### ISSUE TITLE
[PE-D] Assumes only for windows users

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-4/tp#218]
![Screenshot 2022-04-01 at 8.51.28 PM.png](https://raw.githubusercontent.com/gigituang/ped/main/files/a450c29e-a1e9-4ff4-8407-086328850255.png)

instructions were catered towards windows user, but screenshot was for mac OS.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: gigituang/ped#9

**Comment by punnyhuimin** [comment]
Do a separate instruction for mac users to open up the JAR
