### ISSUE TITLE
[PE-D] Command to clear orders only

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-4/tp#225]
### Problem

The `clear` command deletes all contacts and orders, but I only want to delete the orders as there are too many completed orders which I want to archive

### Suggestion

Have a `clear` command just for orders, or for orders which have been completed

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sheimoria/ped#5

**Comment by darshan152** [comment]
This would be a violation of the feature freeze, thus we will not be addressing it
